# Generated by Django 3.1.2 on 2021-01-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='extra',
        ),
    ]
