# Generated by Django 3.1.2 on 2021-01-27 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_delete_feedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_title', models.CharField(max_length=200, unique=True)),
                ('feed_slug', models.CharField(max_length=200, unique=True)),
                ('feed_desc', models.TextField()),
                ('feed_updated_on', models.DateTimeField(auto_now_add=True)),
                ('feed_document', models.FileField(upload_to='', verbose_name='/posts')),
                ('feed_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
