# Generated by Django 3.1.2 on 2021-01-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210128_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='feed_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
