# Generated by Django 3.1.2 on 2021-01-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_feedpost_feed_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedPost',
        ),
    ]
