# Generated by Django 3.1.2 on 2021-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_doc',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
