# Generated by Django 3.1.2 on 2021-01-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_feed_feed_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='posts')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.CreateModel(
            name='ImageVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.video')),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.imagevideomodel'),
        ),
    ]
