# Generated by Django 3.1.2 on 2021-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_feed_feed_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagevideomodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagevideomodel',
            name='video',
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_doc',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageVideoModel',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
