# Generated by Django 3.1.2 on 2021-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210130_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_doc_type',
            field=models.IntegerField(choices=[(0, 'Image'), (1, 'Video')], default=0),
        ),
    ]
