# Generated by Django 3.1.2 on 2021-01-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_feed_feed_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_doc',
        ),
    ]
