# Generated by Django 3.1.2 on 2021-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_feed_feed_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_doc_type',
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_doc',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
