# Generated by Django 3.1.2 on 2021-01-31 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210131_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_doc',
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.feed')),
                ('feed_doc', models.FileField(null=True, upload_to='posts')),
            ],
            bases=('blog.feed',),
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.feed')),
                ('feed_doc', models.FileField(null=True, upload_to='posts')),
            ],
            bases=('blog.feed',),
        ),
    ]
