# Generated by Django 3.1.2 on 2021-01-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210201_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='feed_doc',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
