# Generated by Django 3.1.2 on 2021-01-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210201_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='feed_doc',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='feed_doc',
            new_name='video',
        ),
    ]
