# Generated by Django 3.1.2 on 2021-01-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210201_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed_content',
            new_name='desc',
        ),
    ]
