# Generated by Django 3.1.2 on 2021-01-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210201_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='desc',
            new_name='description',
        ),
    ]
