# Generated by Django 3.1.2 on 2021-02-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_imagepostcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePostComment',
        ),
    ]
