# Generated by Django 3.1.2 on 2021-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210201_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepostcomment',
            name='image_post_comment_email',
            field=models.EmailField(default='eg dekeji1@gmail.com', max_length=254),
        ),
    ]
