# Generated by Django 3.1.2 on 2021-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210201_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopostcomment',
            name='video_post',
        ),
        migrations.DeleteModel(
            name='ImagePostComment',
        ),
        migrations.DeleteModel(
            name='VideoPostComment',
        ),
    ]
